#!/bin/bash

export TORNADO_ROOT=/Users/michalis/repos/TornadoVM
export TORNADO_SDK=${TORNADO_ROOT}/bin/sdk
export LLAMA_ROOT=/Users/michalis/repos/llama3.java-tornadovm
export PATH="${PATH}:${LLAMA_ROOT=}/bin"
